import type { ProfileConfig } from "@/features/profile/types";

export type CurrencyCode = string;
export type DecimalValue = string;
export type ThemeMode = "light" | "dark" | "system";
export type CategoryFlow = "income" | "expense";
export type InstitutionType = "bank" | "broker" | "wallet" | "other";
export type EntryKind =
  | "income"
  | "expense"
  | "internal_transfer"
  | "investment_contribution"
  | "investment_withdrawal"
  | "investment_income"
  | "investment"
  | "reserve"
  | "transfer"
  | "pix"
  | "card_purchase"
  | "card_refund"
  | "card_fee"
  | "card_interest"
  | "credit_payment"
  | "adjustment";
/**
 * The economic nature of an event.  Unlike an entry leg, this is what drives
 * dashboards and makes a transfer or an investment movement unambiguously
 * neutral.
 */
export type FinancialMovementKind =
  | "income"
  | "expense"
  | "internal_transfer"
  | "investment_contribution"
  | "investment_withdrawal"
  | "investment_income"
  | "card_purchase"
  | "card_refund"
  | "card_fee"
  | "card_interest"
  | "credit_payment"
  | "adjustment";
export type InvestmentType =
  | "cash_box"
  | "cdb"
  | "cri"
  | "cra"
  | "fixed_income"
  | "stock"
  | "fii"
  | "etf"
  | "bdr"
  | "crypto"
  | "fund"
  | "pension"
  | "other";
export type RecurrenceFrequency = "once" | "daily" | "weekly" | "biweekly" | "monthly" | "yearly";
export type PaymentMethod = "pix" | "automatic_debit" | "credit_card";

export interface Category {
  id: string;
  name: string;
  icon: string;
  color: string;
  flow: CategoryFlow;
  image?: Blob;
  /** Private object key in Supabase Storage, never a public URL. */
  imagePath?: string;
  isDefault: boolean;
  archivedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ClassificationRule {
  id: string;
  match: string;
  categoryId: string;
  kind: CategoryFlow;
  createdAt: string;
  updatedAt: string;
}

export interface Institution {
  id: string;
  name: string;
  type: InstitutionType;
  bankCode?: string;
  agency?: string;
  accountNumber?: string;
  identifier?: string;
  notes?: string;
  currency: CurrencyCode;
  openingBalance: DecimalValue;
  exchangeRate: DecimalValue;
  exchangeRateAsOf?: string;
  /** Local catalog metadata is optional so records created before the catalog remain valid. */
  catalogId?: InstitutionCatalogId;
  logoKey?: InstitutionLogoKey;
  archivedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export type InstitutionCatalogId =
  | "nubank"
  | "itau"
  | "inter"
  | "bradesco"
  | "santander"
  | "banco-do-brasil"
  | "caixa"
  | "c6"
  | "btg-pactual"
  | "xp"
  | "rico"
  | "clear"
  | "mercado-pago"
  | "picpay"
  | "neon"
  | "wise"
  | "nomad";

export type InstitutionLogoKey = InstitutionCatalogId | "other";

export interface LedgerEntry {
  id: string;
  date: string;
  description: string;
  amount: DecimalValue;
  currency: CurrencyCode;
  brlAmount: DecimalValue;
  kind: EntryKind;
  categoryId?: string;
  institutionId?: string;
  paymentMethod?: PaymentMethod;
  transferGroupId?: string;
  /** Canonical movement this balance-impacting leg belongs to. */
  financialMovementId?: string;
  investmentId?: string;
  assetId?: string;
  creditCardId?: string;
  cardPurchaseId?: string;
  importedDocumentId?: string;
  invoiceKey?: string;
  plannedOccurrenceKey?: string;
  source: "manual" | "import" | "planned" | "reconciliation";
  ignoredFromAnalytics: boolean;
  notes?: string;
  fingerprint?: string;
  pendingReconciliation?: boolean;
  /** Technical settlement generated by the system, hidden from the common ledger. */
  systemGenerated?: boolean;
  createdAt: string;
  updatedAt: string;
}

/** One business event. Its ledger entries are the legs that impact assets. */
export interface FinancialMovement {
  id: string;
  kind: FinancialMovementKind;
  date: string;
  description: string;
  /** Absolute economic amount. It is deliberately separate from signed legs. */
  amount: DecimalValue;
  currency: CurrencyCode;
  brlAmount: DecimalValue;
  categoryId?: string;
  paymentMethod?: PaymentMethod;
  investmentId?: string;
  creditCardId?: string;
  importedDocumentId?: string;
  plannedOccurrenceKey?: string;
  /** Connects investment income recognized during a withdrawal to that withdrawal. */
  relatedMovementId?: string;
  source: LedgerEntry["source"];
  notes?: string;
  fingerprint?: string;
  /** True only for migrated one-sided legacy records which cannot be safely balanced. */
  legacyUnbalanced?: boolean;
  /** Technical movement, such as an invoice settlement, hidden from common lists. */
  systemGenerated?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CreditCard {
  id: string;
  name: string;
  issuer?: InstitutionCatalogId | "other";
  issuerName?: string;
  lastFour?: string;
  network?: CardNetwork;
  cardType?: CardType;
  cardholderName?: string;
  payerInstitutionId?: string;
  limit: DecimalValue;
  closingDay: number;
  dueDay: number;
  currency: CurrencyCode;
  notes?: string;
  archivedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export type CardNetwork = "visa" | "mastercard" | "elo";
export type CardType = "credit" | "debit";

export interface CardPurchase {
  id: string;
  cardId: string;
  description: string;
  amount: DecimalValue;
  currency: CurrencyCode;
  date: string;
  categoryId?: string;
  installments: number;
  /** The statement can show one installment without exposing the original purchase. */
  installmentNumber?: number;
  totalInstallments?: number;
  transactionKind?: "purchase" | "refund" | "fee" | "interest";
  importedDocumentId?: string;
  /** A zero based invoice sequence is derived from the purchase's billing cycle. */
  firstInvoiceKey: string;
  notes?: string;
  ledgerEntryId: string;
  createdAt: string;
  updatedAt: string;
}

export type ImportedDocumentKind = "account_statement" | "card_statement" | "card_invoice";

/** Audit record for an imported file. The original document is never persisted. */
export interface ImportedDocument {
  id: string;
  kind: ImportedDocumentKind;
  contentHash: string;
  source: string;
  institutionId?: InstitutionCatalogId;
  creditCardId?: string;
  periodStart?: string;
  periodEnd?: string;
  closingDate?: string;
  dueDate?: string;
  total?: DecimalValue;
  createdAt: string;
  updatedAt: string;
}

export interface Investment {
  id: string;
  institutionId?: string;
  type: InvestmentType;
  /** Nome comercial da aplicação, por exemplo, "Caixinha Turbo". */
  applicationType?: string;
  name: string;
  ticker?: string;
  quantity: DecimalValue;
  averagePrice: DecimalValue;
  investedAmount: DecimalValue;
  currentPrice: DecimalValue;
  currentValue: DecimalValue;
  dividends: DecimalValue;
  currency: CurrencyCode;
  /** Latest user-controlled conversion into the reporting currency. */
  exchangeRate?: DecimalValue;
  exchangeRateAsOf?: string;
  contractedYield?: string;
  maturityDate?: string;
  quoteStatus: "manual" | "ok" | "error";
  quoteMessage?: string;
  quoteAsOf?: string;
  archivedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface RecurrenceException {
  date: string;
  deleted?: boolean;
  description?: string;
  amount?: DecimalValue;
  kind?: "income" | "expense";
  categoryId?: string;
  institutionId?: string;
  settledEntryId?: string;
  settledMovementId?: string;
  /** Immutable planned snapshot captured when an occurrence is realized. */
  plannedDate?: string;
  plannedDescription?: string;
  plannedAmount?: DecimalValue;
  plannedKind?: "income" | "expense";
  plannedCategoryId?: string;
  plannedInstitutionId?: string;
  paymentMethod?: PaymentMethod;
  creditCardId?: string;
  plannedPaymentMethod?: PaymentMethod;
  plannedCreditCardId?: string;
  effectiveDate?: string;
  effectiveAmount?: DecimalValue;
  /** Snapshot used to make undo safe instead of deleting edited data. */
  generatedFingerprint?: string;
}

export interface PlannedEntry {
  id: string;
  startDate: string;
  description: string;
  amount: DecimalValue;
  kind: "income" | "expense";
  categoryId?: string;
  institutionId?: string;
  /** Legacy plans without this field are interpreted as Pix. */
  paymentMethod?: PaymentMethod;
  creditCardId?: string;
  frequency: RecurrenceFrequency;
  endDate?: string;
  occurrenceCount?: number;
  exceptions: RecurrenceException[];
  createdAt: string;
  updatedAt: string;
}

export interface ImportCandidate {
  id: string;
  date: string;
  description: string;
  amount: DecimalValue;
  currency: CurrencyCode;
  /** Identifier supplied by a statement (OFX FITID, CSV operation ID, etc.). */
  externalId?: string;
  detectedInstitutionId?: InstitutionCatalogId;
  parser: string;
  exchangeRate?: DecimalValue;
  kind: EntryKind;
  categoryId?: string;
  suggestedKind: EntryKind;
  suggestedCategoryId?: string;
  institutionId?: string;
  counterpartyInstitutionId?: string;
  internalTransferSuggestion?: { confidence: number; reason: string };
  confidence: number;
  reason: string;
  source: string;
  include: boolean;
  createInvestment: boolean;
  fingerprint: string;
  duplicate: boolean;
  similarDuplicate?: boolean;
  /** Origem auditável da extração de extrato em PDF/imagem. */
  page?: number;
  extractionSource?: "native" | "ocr";
  rawText?: string;
  needsReview?: boolean;
  reviewReasons?: string[];
  cardTransactionKind?: CardPurchase["transactionKind"];
  installmentNumber?: number;
  totalInstallments?: number;
}

export interface FinanceState {
  categories: Category[];
  classificationRules: ClassificationRule[];
  institutions: Institution[];
  entries: LedgerEntry[];
  financialMovements: FinancialMovement[];
  investments: Investment[];
  creditCards: CreditCard[];
  cardPurchases: CardPurchase[];
  importedDocuments: ImportedDocument[];
  plannedEntries: PlannedEntry[];
  profile: ProfileConfig;
  theme: ThemeMode;
}

export interface PeriodFilter {
  mode: "month" | "year" | "all" | "custom";
  month?: number;
  year?: number;
  startDate?: string;
  endDate?: string;
}

export interface Summary {
  expenses: DecimalValue;
  income: DecimalValue;
  available: DecimalValue;
  invested: DecimalValue;
  categoryTotals: Array<{ categoryId?: string; name: string; color: string; amount: DecimalValue }>;
}
